server:
  port: 8090

spring:
  application:
    name: msvc-invernadero
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
<<<<<<< Updated upstream:MicroserviciosInvernadero/microservicio-sensor/src/main/resources/application.yml
    url: jdbc:mysql://localhost:3307/sensoresdb
=======
    url: jdbc:mysql://localhost:3307/invernaderosdb
>>>>>>> Stashed changes:MicroserviciosInvernadero/microservicio-inv/src/main/resources/application.yml
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: create
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
  config:
    import: optional:configserver:http://localhost:8888

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      dedefaultZone: http://localhost/8761/eureka
