eureka:
  client:
    register-with-eureka: false

server:
  port: 8080

spring:
  application:
    name: msvc-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enbled: true
      routes:
        - id: sensores
          uri: http://localhost:8092
          predicates:
            - Path=/api/sensor/**
        - id: invernaderos
          uri: http://localhost:8091
          predicates:
            - Path=/api/invernadero/**